# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200524_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
