# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
    ]
