# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20200525_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate',
            field=models.CharField(choices=[('Flowers', 'Flowers'), ('Places', 'Places'), ('Animals', 'Animals'), ('People', 'People')], max_length=255),
        ),
    ]
