# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-26 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20200525_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='locs',
        ),
        migrations.AddField(
            model_name='location',
            name='cate',
            field=models.CharField(choices=[('Flowers', 'Flowers'), ('Places', 'Places'), ('Animals', 'Animals'), ('People', 'People')], default='True', max_length=255),
        ),
    ]
