# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20200526_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='cate',
        ),
        migrations.AddField(
            model_name='location',
            name='locs',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Paris', 'Paris'), ('London', 'London'), ('Mexico', 'Mexico'), ('India', 'India')], default='True', max_length=255),
        ),
    ]
